on:
  push:
    branches:
      - main

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".github/labels.yml"
          FILE_BASE64: "LSBuYW1lOiBoYXMgY29uZmxpY3RzCiAgZGVzY3JpcHRpb246IFRoaXMgcHVsbCByZXF1ZXN0IGhhcyBtZXJnZSBjb25mbGljdHMKICBjb2xvcjogY2ZkM2Q3Cg=="
      
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prune: false
  
  label-conflicts:
    runs-on: ubuntu-latest
    needs: create-labels
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
